### ISSUE TITLE
Security Notice & Bug Bounty - Command Injection - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [martinj/node-imagickal#49]
This issue has been generated on-behalf of Mik317 (https://huntr.dev/app/users/Mik317)

# Overview
Affected versions execute arbitrary commands remotely inside the victim's PC. The issue occurs because user input is formatted inside a `command` that will be executed without any checks.

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by JamieSlome** [comment]
@martinj - just looking into why this GitHub Issue has been closed?

A fix has been proposed and is ready to be opened in a pull request to you (https://github.com/418sec/node-imagickal/pull/1).

Cheers! 🍰

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._
